export const productList = [
  {
    name: "follow jacket",
    id: "1",
    price: 7000,
    inCart: 0,
    img: "images/jackets/item3.jpg",
    imgHover: "images/jackets/item3hover.jpg",
  },
  {
    name: "greenland jacket",
    id: "2",
    price: 10000,
    inCart: 0,
    img: "images/jackets/item1.jpg",
    imgHover: "images/jackets/item1hover.jpg",
  },
  {
    name: "holmlia jacket",
    id: "3",
    price: 200000,
    inCart: 0,
    img: "images/jackets/item5.jpg",
    imgHover: "images/jackets/item5hover.jpg",
  },
  {
    name: "oslo jacket",
    id: "4",
    price: 370000,
    inCart: 0,
    img: "images/jackets/item2.jpg",
    imgHover: "images/jackets/item2hover.jpg",
  },
  {
    name: "sarp jacket",
    id: "5",
    price: 170000,
    inCart: 0,
    img: "images/jackets/item4.jpg",
    imgHover: "images/jackets/item4hover.jpg",
  },
  {
    name: "unfollow jacket",
    id: "6",
    price: 1000,
    inCart: 0,
    img: "images/jackets/item6.jpg",
    imgHover: "images/jackets/item6hover.jpg",
  },
];
